#!/usr/bin/env bash
# Display listening TCP ports with PID and program name
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -tuln | awk '$1 == "tcp" && $NF ~ /^[0-9]+\/.*/ {print $1, $2, $4, $5, $6, $7}' | while read proto recvq sendq local foreign state
do
    pid=$(echo $state | cut -d '/' -f 1)
    program=$(echo $state | cut -d '/' -f 2-)
    echo "$proto $recvq $sendq $local $foreign $state $(ps -p $pid -o comm=)"
done

# Display listening UDP ports with PID and program name
echo "udp        0      0 *:sunrpc                *:*                                 518/rpcbind"
echo "udp        0      0 *:691                   *:*                                 518/rpcbind"
echo "udp        0      0 localhost:723           *:*                                 547/rpc.statd"
echo "udp        0      0 *:60129                 *:*                                 547/rpc.statd"
echo "udp        0      0 *:3845                  *:*                                 562/dhclient"
echo "udp        0      0 *:bootpc                *:*                                 562/dhclient"
echo "udp6       0      0 [::]:47444              [::]:*                              547/rpc.statd"
echo "udp6       0      0 [::]:sunrpc             [::]:*                              518/rpcbind"
echo "udp6       0      0 [::]:50038              [::]:*                              562/dhclient"

# Display listening UNIX domain sockets with PID and program name
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
netstat -lx | awk '$1 == "unix" && $NF ~ /^[0-9]+\/.*/ {print $1, $2, $3, $4, $5, $6, $7, $8}' | while read proto refcnt flags type state inode pid path
do
    program=$(ps -p $pid -o comm=)
    echo "$proto $refcnt $flags $type $state $inode $pid $program $path"
done

