#!/bin/bash

# Find and kill the process named "7-highlander"
pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -n "$pid" ]; then
    # Send SIGKILL signal to the process
    kill -9 "$pid"
fi

