#!/usr/bin/env bash
# This script tells a story about each user in /etc/passwd.

while IFS=: read -r username x userid groupid description homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $description"
done < /etc/passwd

