#!/usr/bin/env bash
# This script configures localhost to resolve to 127.0.0.2 and facebook.com to resolve to 8.8.8.8.

# Modify hosts file
sudo sed -i 's/127.0.0.1\slocalhost/127.0.0.2 localhost/g' /etc/hosts
sudo sed -i 's/facebook.com/8.8.8.8/g' /etc/hosts

# Flush DNS cache
sudo systemctl restart systemd-resolved.service

echo "Hosts file updated. Now localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8"

